# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci --ignore-scripts

# Copy the rest of the source code
COPY . ./

# Build the project
RUN npm run build

# Expose port if needed (optional, currently not documented)

# Set the default command
CMD ["node", "build/index.js"]
